org.gradle.jvmargs=-Xmx2048M
java_version_range = >=17

minecraft_version=1.20.1
minecraft_version_range_forge=[1.20.1,1.20.2)
minecraft_version_range_fabric=~1.20.1
enabled_platforms=fabric,forge

deltaboxlib_version=2.0.0
deltaboxlib_version_range_fabric=>=2.0.0,<2.1.0
deltaboxlib_version_range_forge=[2.0.0,2.1.0)

mod_id                    = palegardenbackport
mod_name                  = Pale Garden Backport
mod_license               = MIT
mod_version               = 2.0.0
mod_group                 = com.dannbrown.palegardenbackport
mod_authors               = DannBrown
mod_source                = https://github.com/danbrown/palegardenbackport
pack_format_number        = 15
mod_description           = Sample mod description

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=9.0.8
architectury_version_range_forge = [9.0.8,)
architectury_version_range_fabric = >=9.0.8

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=1.20.1-47.0.19
forge_version_range=[47,)

# https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files
kff_version=4.3.0
kff_version_range=[4,)

# https://fabricmc.net/develop/
fabric_loader_version = 0.16.10
fabric_loader_version_range = >=0.16.10
fabric_api_version = 0.92.3+1.20.1

# https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
fabric_kotlin_version=1.9.5+kotlin.1.8.22
fabric_kotlin_version_range=>=1.9.5+kotlin.1.8.22
