# Done to increase the memory available to gradle.
#fabric.loom.multiProjectOptimisation=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# Mod Properties
mod.version=2.0.0
mod.group=com.dannbrown
mod.id=deltaboxlib
mod.name=Deltabox Lib
mod.description=A library mod for all my other mods
mod.authors=DanBrown_
mod.license=MIT
mod.issue_tracker=
mod.discord=

# Modloader
mc.target=[VERSIONED]
mc.version=[VERSIONED]
fml.version=[VERSIONED]
deps.flk=[VERSIONED]
deps.kff=[VERSIONED]
deps.fapi=[VERSIONED]
deps.fabric_loader=0.16.3
deps.target_loader=[VERSIONED]
deps.target_forge=[VERSIONED]

# Versioned Dependencies
deps.modmenu=[VERSIONED]

